### PR TITLE
Strip non unicode spaces from last author

### PR DESCRIPTION
**Pull request by davismr**
Strip spaces from last author to deal with malformed author fields.

I realise that it would be better to fix the source docs, but these are third party docs and we don't have the option to fix them at source.

### CODE REVIEW

**Comment by cjw296** [comment]
Which bug # on here does this relate to?

**Comment by cjw296** [comment]
Also, how come these are still .xls? Could you source them as .xlsx and use openpyxl instead?

**Comment by davismr** [comment]
Hi Chris,

I didn’t add a bug, as it was a similar issue to #288. Malformed unicode author.

Sadly, can’t get another source, they are from a third party website stuck in the 90s.

Cheers
Michael

**Comment by wh5a** [comment]
@davismr @cjw296 But this change is causing a UnicodeDecodeError on my file here: https://www.dropbox.com/s/c6orcdr2zsjtjny/6.27%201100246948003F%20%E9%80%9F%E9%80%92%E4%B8%AD%E5%9B%BD999-56056033%28177%29.xls?dl=0

**Comment by cjw296** [comment]
@davismr and @wh5a - can you, between the two of you, figure out what the problem is here and get a PR in for it?

**Comment by davismr** [comment]
@wh5a I tested your file from dropbox, and it worked fine in both python2 and python3 for both trunk and last release. Can you send me your traceback, and details of your environment as I can't replicate your issue. It might be that dropbox has changed the file on upload/download, if you could test with that and see if it gives the same error.

**Comment by wh5a** [comment]
@davismr I'm sorry I uploaded the wrong file. I've uploaded the right file to https://www.dropbox.com/s/z0g4zx5okg2jzlb/a.xls?dl=0

I also created #347 for this issue. Thanks!

**Pull request merged**
