### PR TITLE
Allow for xlsx files to contain workbook2.xml instead of the expected…

### PR DESCRIPTION
**Pull request by gowdy**
… workbook.xml. Add test for this.

### CODE REVIEW

**Comment by gowdy** [comment]
This is to fix Issue #241

**Comment by jdufresne** [comment]
I'm unfamiliar with the details of the issue. Under what conditions would `workbook2.xml` be used instead of `workbook.xml`? Is there any documentation to support this? I noticed [openpyxl](https://openpyxl.readthedocs.io/en/stable/) fails to open this document with `KeyError: "There is no item named 'xl/workbook.xml' in the archive"` as does LibreOffice.

**Comment by gowdy** [comment]
Hi Jon,

I don't know which circumstance causes this, but it occurs for a file I
downloaded from a data source.

regards,

Stephen.

**Comment by jdufresne** [comment]
As both LibreOffice and openpyxl do not support `workbook2.xml`, I'm hesitant to merge this. If you can provide documentation that this is indeed part of the xlsx, I'll quickly change my mind and reopen the issue. At the moment, my first impression is this name may be nonstandard.

If so, might I suggest filing a bug with the data source explaining that they are delivering a nonstandard .xlsx file.

As a last resort, you could unzip and post process the file before passing it to xlrd.

Thanks for the PR and report.

**Pull request closed without merging**
