### PR TITLE
Use Element.iter() instead of deprecated getiterator()

### PR DESCRIPTION
**Pull request by jikamens**

### CODE REVIEW

**Comment by sjmachin** [comment]
Firstly, please leave pythondoc.py alone. Its only purpose is to generate docs from the source. It need Python 2.4.

Secondly, we profess to support xlrd running under Python 2.7 ... see https://pypi.python.org/pypi/xlrd

Please try iter and failover to getiterator.

**Comment by jikamens** [comment]
>Firstly, please leave pythondoc.py alone. Its only purpose is to generate docs from the source. It needs Python 2.4.

Can you clarify why pythondoc.py needs teo work with Python 2.4 if you only profess in README.html to support Python 2.6 - 2.7? I'm confused.

**Comment by sjmachin** [comment]
That instance of pythondoc.py is NOT part of the xlrd runtime. It is not for general consumption. I am the only person who knows/cares about it. It works by compiling the code and rummaging through the syntax tree that is generated. It is stuck on 2.4 because the structure of that tree changed and the original author (effbot) no longer maintains it.

**Comment by jikamens** [comment]
>That instance of pythondoc.py is NOT part of the xlrd runtime...

Got it.

Concerning your other suggestion:

>Please try iter and failover to getiterator.

I think I should check at module load time which is available and use that one later, rather than trying `iter` every single time and failing over to `getiterator` if `iter` fails, since the try/except is more expensive than a conditional. What do you think?

**Comment by sjmachin** [comment]
Yes, do it at module (xlsx) level, set a global flag ET_has_iter... model your code on that for ET_has_iterparse. BTW the iter we are looking at is the so-named method of the ElementTree class, not the Element class.

**Comment by vadmium** [comment]
As far as I know, using the old getiterator() method does not trigger any actual deprecation warnings, and there don’t seem to be any plans to actually remove it. Perhaps it would be simplest to keep the code as it is for the time being? Or just add a comment explaining why the deprecated method is used.

**Comment by jikamens** [comment]
>As far as I know, using the old getiterator() method does not trigger any actual deprecation warnings,

Yes, it does. If it didn't, we wouldn't have bothered to submit a PR.

I'll try to clean it up as requested when I get a chance.

**Comment by vadmium** [comment]
Sorry, I see you are right @jikamens, so now I support the proposal :)

Before I only checked in C Python 3.4, which uses the C implementation by default. However I see that other versions (e.g. native Python 2.7 version) do emit a PendingDeprecationWarning.

**Comment by jikamens** [comment]
Please take a look at my new attempt to get this right and let me know what you think. Thanks.

**Comment by sjmachin** [comment]
Please don't do 'iter' in dict(ET.fromstring(blah)), which produces an Element instance.
We are using an ElementTree instance.
Please do ET_has_iter = hasattr(ET.ElementTree, 'iter')

**Comment by jikamens** [comment]
OK, how's it now?

**Comment by sjmachin** [comment]
Good enough :-)

**Pull request merged**
