### PR TITLE
[hotfix] do-merge-single-cell

### PR DESCRIPTION
**Pull request by icereval**
I've seen a few instances where we get a single cell merge showing up in documents, excel opens them correctly however xlrd will crash with a ValueError in 0.9.3.

### CODE REVIEW

**Comment by bartbkr** [comment]
It would be great if this could get merged into master. This fix was the only way that xlrd was usable for the workbooks I am working with.

**Comment by cjw296** [comment]
It needs a unit test adding...

**Comment by cjw296** [comment]
...not tests were forthcoming.

**Comment by cjw296** [comment]
Wait, now I've seen the context, I understand and, even without a test, might as well merge!

**Pull request merged**
