### PR TITLE
Add pypy, pypy3, and 3.5 to Travis

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by cjw296** [comment]
@scop - I'm afraid that pypy doesn't work, so I'll be removing it:

https://travis-ci.org/python-excel/xlrd/builds/134911140

**Comment by scop** [comment]
I'm fairly certain I tested the pypy's with Travis it before submitting the PR. But I have no problem removing them now if they don't work any more / after all.

**Comment by cjw296** [comment]
If you can get the current master branch worth again, happy to add them back. They both hung in the above build,,,

(lots has changed on master since you put in the pull request...)

**Comment by scop** [comment]
pypy3 is at cpython 3.2 level at the moment, so no need to try with is as 3.2 support has been dropped.

I debugged the test run on pypy a bit, and it hangs in `test_sap_generate_xls`. I'm not going to spend more time on this at the moment, but here's some data if someone's interested: It is not because it's the last test method in that test case (removing this particular test makes the case and suite pass), nor does adding `.release_resources()` to the `open_workbook` call help.

**Pull request merged**
