### PR TITLE
Change to default encodings and codepages, for better compatibility

### PR DESCRIPTION
**Pull request by tltx**
This change will increase the encoding compatibility. It has been used on a lot of documents from all over the world.

### CODE REVIEW

**Comment by cjw296** [comment]
I'm afraid it also causes code coverage to drop. Can you add sufficient tests to fix that, please?
Also would want @sjmachin 's thoughts on this...

**Comment by jdufresne** [comment]
Is there documentation to suggest that iso-8859-1 is the default encoding? (Or any other encoding.) Or is this simply the most common through experience?

**Comment by jdufresne** [comment]
Could you add a test to exercise this new behavior?

**Comment by cjw296** [comment]
@tltx - hmm, not sure your argument makes sense... xlrd is not only used by people in Western Europe ;-)

**Comment by boxed** [comment]
@cjw296 the current behavior is ascii. Changing to latin-1 will make some files work, and break no files. It's a pure win.

**Pull request merged**
