### PR TITLE
support BIFF4 files with missing FORMAT records

### PR DESCRIPTION
**Pull request by stratoukos**
Adds support for BIFF4 with missing FORMAT records. This is the same issue as #57 (in fact I used the same test xls file).

Some possible issues with this PR:

1. I also silenced an error about missing FORMAT records. Another approach would be to emit some kind of warning.
2. I'm not sure about `Format._xf_index_to_xl_type_map`'s purpose, so I defaulted to using `XL_CELL_TEXT`. I also tried `XL_CELL_EMPTY` and `XL_CELL_BLANK`, but didn't notice any difference.
3. On PR #57 @cjw296 commented that FORMAT records are not optional in BIFF4 files, but seemed willing to merge some fix for this. I guess it's up to the maintainers if this fix should be merged.

Thanks.

### CODE REVIEW

**Comment by stratoukos** [comment]
Hmmm, tests are failing in python3. I'll have to investigate further.

**Comment by stratoukos** [comment]
Turns out the test failure was unrelated to my fix. 

The test file is also missing a WINDOW2 record, which meant that `Sheet.cached_page_break_preview_mag_factor` would be None. This was later compared to an int which is an error in python 3.

Since I don't know how to create a BIFF4 file with a WINDOW2 record, but missing FORMAT records, I added some defaults for `Sheet.cached_page_break_preview_mag_factor` and `Sheet.cached_normal_view_mag_factor`, so we can now parse files without a WINDOW2 record. There were already some defaults in place, but they were only used for BIFF2 files and BIFF3-BIFF5 files with a WINDOW2 record.

I also rebased on master.

**Comment by stratoukos** [comment]
Hey.

Any chance of this being merged? Is there anything I can do to improve the patch?

Thanks!

**Comment by gabriel-laet** [comment]
@stratoukos Your patch fixed an issue we were having with an old Excel file, thanks for pushing this.

**Comment by cjw296** [comment]
@sjmachin - what are your views?

**Comment by cjw296** [comment]
Actually, this addresses comments made in #57, I think we're good to merge.

**Pull request merged**
